## Numpy

Импортировать NumPy под именем np

In [2]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [2]:
vec0 = np.array([0]*10)
print(vec0)

[0 0 0 0 0 0 0 0 0 0]


Создать вектор размера 10, заполненный единицами

In [3]:
vec1 = np.array([1]*10)
print(vec1)

[1 1 1 1 1 1 1 1 1 1]


Создать вектор размера 10, заполненный числом 2.5

In [4]:
vec2 = np.array([2.5]*10)
print(vec2)

[ 2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5]


Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [8]:
vec3 = np.array([0]*10)
vec3[4] = 1
print(vec3)

[0 0 0 0 1 0 0 0 0 0]


Развернуть вектор (первый становится последним)

In [9]:
reversed_vec3 = vec3[::-1]
print(reversed_vec3)

[0 0 0 0 0 1 0 0 0 0]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [3]:
import numpy as np
matrix_it = np.random.randint(0, 8, (3, 3))
matrix_fl = np.random.uniform(0, 8, (3, 3))
print(matrix_it)
print(matrix_fl)

[[2 6 6]
 [7 3 3]
 [3 5 5]]
[[ 2.19139971  0.63670326  5.79364051]
 [ 4.07634544  6.72248731  3.36014005]
 [ 2.4925152   3.32694051  4.26935359]]


Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [18]:
vec_non_zero = np.nonzero([1,2,0,0,4,0])
print(vec_non_zero)

(array([0, 1, 4], dtype=int64),)


Создать 3x3 единичную матрицу

In [6]:
matrix_one = np.eye(3,3)
print(matrix_one)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Создать массив 3x3x3 со случайными значениями

In [4]:
import numpy as np
matrix_fl = np.random.uniform(0, 8, (3, 3, 3))
print(matrix_fl)

[[[ 6.12295274  6.21903476  0.99245826]
  [ 6.34638131  7.26755652  1.24479041]
  [ 1.72683889  0.96471897  2.65146341]]

 [[ 0.94619987  0.69088543  5.84986174]
  [ 4.62912513  1.51497682  6.71242961]
  [ 0.61271555  0.35173725  5.77291565]]

 [[ 6.09076204  2.69353141  6.00350788]
  [ 3.81584966  1.87485233  4.92862217]
  [ 5.28536142  4.22076695  6.82211365]]]


Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [17]:
import numpy as np

vec30 = np.random.random(30)
print(vec30)
print(vec30.mean())

[ 0.88509294  0.90419762  0.0104217   0.07455674  0.24462921  0.13330475
  0.6979251   0.39820488  0.88312219  0.18100751  0.43249917  0.0181432
  0.69143786  0.46969065  0.12822219  0.89133705  0.91820362  0.07312099
  0.04544794  0.4385729   0.60172093  0.31022703  0.68190824  0.20901315
  0.5196043   0.56598883  0.44116739  0.13755616  0.21354319  0.13337189]
0.411107978013


Перемножить матрицы 5x3 и 3x2

In [21]:
import numpy as np
m1 = np.random.randint(0, 8, (5, 3))
m2 = np.random.randint(0, 8, (3, 2))
print(m1,m2)
print(m1.dot(m2))

[[5 4 4]
 [4 3 5]
 [4 2 1]
 [0 7 6]
 [0 1 6]] [[1 1]
 [6 5]
 [0 0]]
[[29 25]
 [22 19]
 [16 14]
 [42 35]
 [ 6  5]]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [26]:
vec10 = np.linspace(0,1,12)[1:-1]
print(vec10)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


Заменить максимальный элемент на ноль

In [29]:
vec10[vec10.argmax()] = 0


0.909090909091


Преобразовать массив из float в int

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [36]:
import scipy.spatial
from sklearn.metrics.pairwise import euclidean_distances

M = np.random.randint(0, 5, (10, 2))
print(M)
scipy_D = scipy.spatial.distance.cdist(M,M)
sciln_D = euclidean_distances(M,M) 
print(scipy_D)
print('\n','********************************************', '\n')
print(sciln_D)

[[3 2]
 [0 4]
 [2 2]
 [2 4]
 [3 0]
 [0 0]
 [0 1]
 [2 3]
 [0 1]
 [1 1]]
[[ 0.          3.60555128  1.          2.23606798  2.          3.60555128
   3.16227766  1.41421356  3.16227766  2.23606798]
 [ 3.60555128  0.          2.82842712  2.          5.          4.          3.
   2.23606798  3.          3.16227766]
 [ 1.          2.82842712  0.          2.          2.23606798  2.82842712
   2.23606798  1.          2.23606798  1.41421356]
 [ 2.23606798  2.          2.          0.          4.12310563  4.47213595
   3.60555128  1.          3.60555128  3.16227766]
 [ 2.          5.          2.23606798  4.12310563  0.          3.
   3.16227766  3.16227766  3.16227766  2.23606798]
 [ 3.60555128  4.          2.82842712  4.47213595  3.          0.          1.
   3.60555128  1.          1.41421356]
 [ 3.16227766  3.          2.23606798  3.60555128  3.16227766  1.          0.
   2.82842712  0.          1.        ]
 [ 1.41421356  2.23606798  1.          1.          3.16227766  3.60555128
   2.8284271

Случайно расположить p элементов в 2D массив

In [48]:
import numpy as np
import random
n = 10
p = 3
a = np.random.choice(range(n*n), 1, replace=False)
M = np.zeros((n,n))
A = np.put(M, np.random.choice(range(n*n), p, replace=False), a)
print(M)

print('\n'+'********************** Вариант 2 ******************************'+ '\n')

M = np.zeros((n,n))
a = np.random.choice(range(n*n), p, replace=False)
np.put(M, range(p), a)
M.shape = (1,n*n)
A = np.random.shuffle(M[0])
M.shape = (n,n)
print(M)

[[  0.   0.  68.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  68.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  68.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]

********************** Вариант 2 ******************************

[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.  97.   0.]
 [  0.   0.   0.   0.   0.  88.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0. 

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [52]:
import numpy as np

n = 3
vec = [1, 2, 3, 4, 5]
new_vec = np.zeros((len(vec)-1)*n+len(vec))
print(new_vec)
new_vec[::n+1] = vec
print(new_vec)



[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


Найти наиболее частое значение в массиве

Найти n наибольших значений в массиве

## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

Посмотреть первые 5 записей

Сколько наблюдений в наборе данных?


Сколько столбцов в наборе данных?

Напечатайте все названия столбцов

Какое название у 105 столбца?

Какой тип наблюдений в 105 столбце?

Как проиндексирован набор данных?

Каково значение имени продукта в 19-м наблюдении?

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

Как много продуктов стоят более чем $10.00?

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

Отсортировать по имени предмета

Сколько было заказано самого дорогого предмета?

Сколько раз был заказан предмет "Veggie Salad Bowl"?

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?