## Numpy

Импортировать NumPy под именем np

In [2]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [2]:
vec0 = np.array([0]*10)
print(vec0)

[0 0 0 0 0 0 0 0 0 0]


Создать вектор размера 10, заполненный единицами

In [3]:
vec1 = np.array([1]*10)
print(vec1)

[1 1 1 1 1 1 1 1 1 1]


Создать вектор размера 10, заполненный числом 2.5

In [4]:
vec2 = np.array([2.5]*10)
print(vec2)

[ 2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5]


Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [8]:
vec3 = np.array([0]*10)
vec3[4] = 1
print(vec3)

[0 0 0 0 1 0 0 0 0 0]


Развернуть вектор (первый становится последним)

In [9]:
reversed_vec3 = vec3[::-1]
print(reversed_vec3)

[0 0 0 0 0 1 0 0 0 0]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [3]:
import numpy as np
matrix_it = np.random.randint(0, 8, (3, 3))
matrix_fl = np.random.uniform(0, 8, (3, 3))
print(matrix_it)
print(matrix_fl)

[[2 6 6]
 [7 3 3]
 [3 5 5]]
[[ 2.19139971  0.63670326  5.79364051]
 [ 4.07634544  6.72248731  3.36014005]
 [ 2.4925152   3.32694051  4.26935359]]


Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [18]:
vec_non_zero = np.nonzero([1,2,0,0,4,0])
print(vec_non_zero)

(array([0, 1, 4], dtype=int64),)


Создать 3x3 единичную матрицу

In [6]:
matrix_one = np.eye(3,3)
print(matrix_one)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Создать массив 3x3x3 со случайными значениями

In [4]:
import numpy as np
matrix_fl = np.random.uniform(0, 8, (3, 3, 3))
print(matrix_fl)

[[[ 6.12295274  6.21903476  0.99245826]
  [ 6.34638131  7.26755652  1.24479041]
  [ 1.72683889  0.96471897  2.65146341]]

 [[ 0.94619987  0.69088543  5.84986174]
  [ 4.62912513  1.51497682  6.71242961]
  [ 0.61271555  0.35173725  5.77291565]]

 [[ 6.09076204  2.69353141  6.00350788]
  [ 3.81584966  1.87485233  4.92862217]
  [ 5.28536142  4.22076695  6.82211365]]]


Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [17]:
import numpy as np

vec30 = np.random.random(30)
print(vec30)
print(vec30.mean())

[ 0.88509294  0.90419762  0.0104217   0.07455674  0.24462921  0.13330475
  0.6979251   0.39820488  0.88312219  0.18100751  0.43249917  0.0181432
  0.69143786  0.46969065  0.12822219  0.89133705  0.91820362  0.07312099
  0.04544794  0.4385729   0.60172093  0.31022703  0.68190824  0.20901315
  0.5196043   0.56598883  0.44116739  0.13755616  0.21354319  0.13337189]
0.411107978013


Перемножить матрицы 5x3 и 3x2

In [21]:
import numpy as np
m1 = np.random.randint(0, 8, (5, 3))
m2 = np.random.randint(0, 8, (3, 2))
print(m1,m2)
print(m1.dot(m2))

[[5 4 4]
 [4 3 5]
 [4 2 1]
 [0 7 6]
 [0 1 6]] [[1 1]
 [6 5]
 [0 0]]
[[29 25]
 [22 19]
 [16 14]
 [42 35]
 [ 6  5]]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [26]:
vec10 = np.linspace(0,1,12)[1:-1]
print(vec10)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


Заменить максимальный элемент на ноль

In [29]:
vec10[vec10.argmax()] = 0


0.909090909091


Преобразовать массив из float в int

In [2]:
import numpy as np
vec = np.arange(10, dtype=np.float32)
print(vec)
vec = vec.astype(np.int32, copy=False)
print(vec)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[0 1 2 3 4 5 6 7 8 9]


Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [36]:
import scipy.spatial
from sklearn.metrics.pairwise import euclidean_distances

M = np.random.randint(0, 5, (10, 2))
print(M)
scipy_D = scipy.spatial.distance.cdist(M,M)
sciln_D = euclidean_distances(M,M) 
print(scipy_D)
print('\n','********************************************', '\n')
print(sciln_D)

[[3 2]
 [0 4]
 [2 2]
 [2 4]
 [3 0]
 [0 0]
 [0 1]
 [2 3]
 [0 1]
 [1 1]]
[[ 0.          3.60555128  1.          2.23606798  2.          3.60555128
   3.16227766  1.41421356  3.16227766  2.23606798]
 [ 3.60555128  0.          2.82842712  2.          5.          4.          3.
   2.23606798  3.          3.16227766]
 [ 1.          2.82842712  0.          2.          2.23606798  2.82842712
   2.23606798  1.          2.23606798  1.41421356]
 [ 2.23606798  2.          2.          0.          4.12310563  4.47213595
   3.60555128  1.          3.60555128  3.16227766]
 [ 2.          5.          2.23606798  4.12310563  0.          3.
   3.16227766  3.16227766  3.16227766  2.23606798]
 [ 3.60555128  4.          2.82842712  4.47213595  3.          0.          1.
   3.60555128  1.          1.41421356]
 [ 3.16227766  3.          2.23606798  3.60555128  3.16227766  1.          0.
   2.82842712  0.          1.        ]
 [ 1.41421356  2.23606798  1.          1.          3.16227766  3.60555128
   2.8284271

Случайно расположить p элементов в 2D массив

In [48]:
import numpy as np
import random
n = 10
p = 3
a = np.random.choice(range(n*n), 1, replace=False)
M = np.zeros((n,n))
A = np.put(M, np.random.choice(range(n*n), p, replace=False), a)
print(M)

print('\n'+'********************** Вариант 2 ******************************'+ '\n')

M = np.zeros((n,n))
a = np.random.choice(range(n*n), p, replace=False)
np.put(M, range(p), a)
M.shape = (1,n*n)
A = np.random.shuffle(M[0])
M.shape = (n,n)
print(M)

[[  0.   0.  68.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  68.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  68.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]

********************** Вариант 2 ******************************

[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.  97.   0.]
 [  0.   0.   0.   0.   0.  88.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0. 

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [52]:
import numpy as np

n = 3
vec = [1, 2, 3, 4, 5]
new_vec = np.zeros((len(vec)-1)*n+len(vec))
print(new_vec)
new_vec[::n+1] = vec
print(new_vec)



[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


Найти наиболее частое значение в массиве

In [13]:
import numpy as np

vec = np.random.randint(0,100,100)
print(vec)
print(np.bincount(vec).argmax())


[53 12 23 11 93  3 12 49 31 19 67 66 80 36 38 39 21 23 43 73 29 23 93 98 31
 35 23 68  7 32 42 74 31 79 43 86 30 94  0 40 24 29 66  9 45  8 48 72 61 91
 76  4 59 86 91 44 31 38 89 85 91 76 97 52 76  0 82 48 43 69 16 49 38 82  0
 23 38 70 38 36 47 63 38 11 25 68 47 56 16 22 10  3 50  6  4 82 92 68 12 25]
38


Найти n наибольших значений в массиве

In [23]:
import numpy as np

n=5
vec = np.random.randint(0,100,100)
print(vec)
vec.sort()
print(vec)
l = len(vec)
print(vec[l-n:l])


[66 28 80 77 78 20 32 27 99 81  8 40 18 73 19 96 42 49 23 71 63 50 93 19 70
 69 65 13 37 59 56 69 11 73 82 55 62  1  3 10 58 86  6  1 58 37 56 56 38 26
 56 80 79 50 24 38  1 30 77 20 89 28 22 36 95 32 84 24 98 83 14 22 77 17 94
 36  6 21 60 79 12 97 86 29 52 68 60 57 36 58  5 66 16 27 62 17 24 35 82 46]
[ 1  1  1  3  5  6  6  8 10 11 12 13 14 16 17 17 18 19 19 20 20 21 22 22 23
 24 24 24 26 27 27 28 28 29 30 32 32 35 36 36 36 37 37 38 38 40 42 46 49 50
 50 52 55 56 56 56 56 57 58 58 58 59 60 60 62 62 63 65 66 66 68 69 69 70 71
 73 73 77 77 77 78 79 79 80 80 81 82 82 83 84 86 86 89 93 94 95 96 97 98 99]
[95 96 97 98 99]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food
(jupyter notebook --NotebookApp.iopub_data_rate_limit=1.0e10)
или
C:\Users\User\.jupyter\jupyter_notebook_config.py

In [1]:
import pandas as pd
pd.set_option('display.max_rows',5)

#pd.set_option('display.max_columns',5)
food = pd.read_csv('en.openfoodfacts.org.products.tsv', lineterminator='\n',error_bad_lines=False, sep="\t", low_memory=False)

Посмотреть первые 5 записей

In [2]:
#handle = open("en.openfoodfacts.org.products.csv", "r")
#for number in range(5):
    #data = handle.readline() # read just one line
    #print(data)
#handle.close()
print(food.head(5))


            code                                                url  \
0  0000000003087  http://world-en.openfoodfacts.org/product/0000...   
1  0000000004530  http://world-en.openfoodfacts.org/product/0000...   
2  0000000004559  http://world-en.openfoodfacts.org/product/0000...   
3  0000000016087  http://world-en.openfoodfacts.org/product/0000...   
4  0000000016094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

   last_modified_t last_modified_datetime                    product_name  \
0       1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1       14890699

Сколько наблюдений в наборе данных?


In [5]:
print(food.shape[0])

356001


Сколько столбцов в наборе данных?

In [6]:
print(food.shape[1])

163


Напечатайте все названия столбцов

In [12]:
print(food.columns.values.tolist())
print(list(food))

['code', 'url', 'creator', 'created_t', 'created_datetime', 'last_modified_t', 'last_modified_datetime', 'product_name', 'generic_name', 'quantity', 'packaging', 'packaging_tags', 'brands', 'brands_tags', 'categories', 'categories_tags', 'categories_en', 'origins', 'origins_tags', 'manufacturing_places', 'manufacturing_places_tags', 'labels', 'labels_tags', 'labels_en', 'emb_codes', 'emb_codes_tags', 'first_packaging_code_geo', 'cities', 'cities_tags', 'purchase_places', 'stores', 'countries', 'countries_tags', 'countries_en', 'ingredients_text', 'allergens', 'allergens_en', 'traces', 'traces_tags', 'traces_en', 'serving_size', 'no_nutriments', 'additives_n', 'additives', 'additives_tags', 'additives_en', 'ingredients_from_palm_oil_n', 'ingredients_from_palm_oil', 'ingredients_from_palm_oil_tags', 'ingredients_that_may_be_from_palm_oil_n', 'ingredients_that_may_be_from_palm_oil', 'ingredients_that_may_be_from_palm_oil_tags', 'nutrition_grade_uk', 'nutrition_grade_fr', 'pnns_groups_1', 

Какое название у 105 столбца?

In [3]:
food.columns.values.tolist()[104]

'-glucose_100g'

Какой тип наблюдений в 105 столбце?

In [4]:
food.dtypes[104]

dtype('float64')

Как проиндексирован набор данных?

In [22]:
print(food.index)

RangeIndex(start=0, stop=356001, step=1)


Каково значение имени продукта в 19-м наблюдении?

In [18]:
print(food[19:20]['product_name'])

19    Organic Oat Groats
Name: product_name, dtype: object


## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [97]:
import urllib.request
import pandas as pd
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
urllib.request.urlretrieve(url, 'chipotle.tsv')

pd.set_option('display.max_rows',5)
chipo = pd.read_csv('chipotle.tsv',error_bad_lines=False, sep="\t")
print(chipo.head(10))
print(chipo.dtypes[4])

    order_id  quantity                     item_name  \
0          1         1  Chips and Fresh Tomato Salsa   
1          1         1                          Izze   
..       ...       ...                           ...   
8          4         1              Steak Soft Tacos   
9          5         1                 Steak Burrito   

                                   choice_description item_price  
0                                                 NaN     $2.39   
1                                        [Clementine]     $3.39   
..                                                ...        ...  
8   [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...     $9.25   
9   [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...     $9.25   

[10 rows x 5 columns]
object


Как много продуктов стоят более чем $10.00?

In [98]:
chipo[['item_price']] = chipo.item_price.str.replace(r"\$", r"", True).astype('float32')
print(chipo[chipo.item_price > 10])

      order_id  quantity           item_name  \
4            2         2        Chicken Bowl   
5            3         1        Chicken Bowl   
...        ...       ...                 ...   
4618      1833         1       Steak Burrito   
4619      1834         1  Chicken Salad Bowl   

                                     choice_description  item_price  
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...       16.98  
5     [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...       10.98  
...                                                 ...         ...  
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...       11.75  
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...       11.25  

[1130 rows x 5 columns]


Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [99]:

print(chipo[['item_name','item_price']])


                         item_name  item_price
0     Chips and Fresh Tomato Salsa        2.39
1                             Izze        3.39
...                            ...         ...
4620            Chicken Salad Bowl        8.75
4621            Chicken Salad Bowl        8.75

[4622 rows x 2 columns]


Отсортировать по имени предмета

In [1]:
import pandas as pd

chipo = pd.read_csv('chipotle.tsv',error_bad_lines=False, sep="\t")
print(chipo)
chipo = chipo.set_index('item_name')
chipo.sort_index()

      order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
5            3         1                           Chicken Bowl   
6            3         1                          Side of Chips   
7            4         1                          Steak Burrito   
8            4         1                       Steak Soft Tacos   
9            5         1                          Steak Burrito   
10           5         1                    Chips and Guacamole   
11           6         1                   Chicken Crispy Tacos   
12           6         1                     Chicken Soft Tacos   
13           7         1                           Chicken Bow

order_id  quantity  \
item_name                               
6 Pack Soft Drink      1360         2   
6 Pack Soft Drink       148         1   
6 Pack Soft Drink       749         1   
6 Pack Soft Drink       754         1   
6 Pack Soft Drink      1076         1   
6 Pack Soft Drink      1373         1   
6 Pack Soft Drink       230         1   
6 Pack Soft Drink       774         1   
6 Pack Soft Drink       776         1   
6 Pack Soft Drink       784         1   
6 Pack Soft Drink      1537         1   
6 Pack Soft Drink       129         1   
6 Pack Soft Drink       798         1   
6 Pack Soft Drink       481         1   
6 Pack Soft Drink      1554         1   
6 Pack Soft Drink       465         1   
6 Pack Soft Drink      1558         1   
6 Pack Soft Drink       849         1   
6 Pack Soft Drink      1196         1   
6 Pack Soft Drink      1803         1   
6 Pack Soft Drink      1664         1   
6 Pack Soft Drink      1666         1   
6 Pack Soft Drink      1800         1   
6 Pack Soft Drink      1798         1   
6 Pack Soft Drink      1525         1   
6 Pack Soft Drink       949         1   
6 Pack Soft Drink      1248         1   
6 Pack Soft Drink      1253         1   
6 Pack Soft Drink       264         1   
6 Pack Soft Drink       422         1   
...                     ...       ...   
Veggie Salad           1192         1   
Veggie Salad           1263         1   
Veggie Salad           1635         1   
Veggie Salad            686         1   
Veggie Salad           1094         1   
Veggie Salad Bowl      1677         1   
Veggie Salad Bowl       760         1   
Veggie Salad Bowl       195         1   
Veggie Salad Bowl      1289         1   
Veggie Salad Bowl       896         1   
Veggie Salad Bowl       913         1   
Veggie Salad Bowl      1805         1   
Veggie Salad Bowl      1321         1   
Veggie Salad Bowl        83         1   
Veggie Salad Bowl       394         1   
Veggie Salad Bowl       536         1   
Veggie Salad Bowl       869         1   
Veggie Salad Bowl      1700         1   
Veggie Salad Bowl       128         1   
Veggie Salad Bowl      1818         1   
Veggie Salad Bowl      1066         1   
Veggie Salad Bowl       207         1   
Veggie Salad Bowl      1646         1   
Veggie Soft Tacos       304         1   
Veggie Soft Tacos      1559         2   
Veggie Soft Tacos       948         1   
Veggie Soft Tacos       322         1   
Veggie Soft Tacos      1132         1   
Veggie Soft Tacos       688         1   
Veggie Soft Tacos       567         1   

                                                  choice_description  \
item_name                                                              
6 Pack Soft Drink                                        [Diet Coke]   
6 Pack Soft Drink                                        [Diet Coke]   
6 Pack Soft Drink                                             [Coke]   
6 Pack Soft Drink                                        [Diet Coke]   
6 Pack Soft Drink                                             [Coke]   
6 Pack Soft Drink                                             [Coke]   
6 Pack Soft Drink                                        [Diet Coke]   
6 Pack Soft Drink                                        [Diet Coke]   
6 Pack Soft Drink                                             [Coke]   
6 Pack Soft Drink                                        [Diet Coke]   
6 Pack Soft Drink                                             [Coke]   
6 Pack Soft Drink                                           [Sprite]   
6 Pack Soft Drink                                        [Diet Coke]   
6 Pack Soft Drink                                             [Coke]   
6 Pack Soft Drink                                        [Diet Coke]   
6 Pack Soft Drink                                             [Coke]   
6 Pack Soft Drink                                        [Diet Coke]   
6 Pack Soft Drink                                             [Coke

Сколько было заказано самого дорогого предмета?

In [14]:
import pandas as pd

chipo = pd.read_csv('chipotle.tsv',error_bad_lines=False, sep="\t")
chipo[['item_price']] = chipo.item_price.str.replace(r"\$", r"", True).astype('float32')
#max_row = np.argmax(df['A'].values)
max_row = chipo['item_price'].argmax()
line_max = chipo['item_price'].values[max_row]
print(line_max)
print(len(chipo[chipo.item_price == line_max]))
chipo[chipo.item_price == line_max]['quantity'].values[0]

44.25
1


15

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [113]:
import pandas as pd

chipo = pd.read_csv('chipotle.tsv',error_bad_lines=False, sep="\t")
print(len(chipo[chipo.item_name == 'Veggie Salad Bowl']))

18


Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [119]:
chipo[['quantity']].apply(pd.to_numeric)
print(chipo[chipo.item_name == 'Canned Soda'][chipo.quantity > 1])
print(len(chipo[chipo.item_name == 'Canned Soda'][chipo.quantity > 1]))

      order_id  quantity    item_name choice_description item_price
18           9         2  Canned Soda           [Sprite]     $2.18 
51          23         2  Canned Soda     [Mountain Dew]     $2.18 
...        ...       ...          ...                ...        ...
3592      1440         2  Canned Soda        [Diet Coke]     $2.18 
3866      1550         2  Canned Soda     [Mountain Dew]     $2.18 

[20 rows x 5 columns]
20


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until
